defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:12

version: 2.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Check snyk version
          command: npm ls snyk
      - run:
          name: Run snyk protect
          command: npm run snyk-protect
      - run:
          name: Test patches
          command: npm t

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - test
